name: Check
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn
      - run: |
          yarn run lint
